version: '2'

services:
  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./docker/collectd/collectd.conf:/etc/collectd/collectd.conf
  influxdb:
    image: influxdb:1.4
    ports:
      - "8086:8086"
      - "8088:8088"
      - "25826:25826/udp"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
      - ./docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./docker/influxdb/types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana:5.1.1
    user: "root"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./docker/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./docker/grafana/Dashboard.json:/var/lib/grafana/dashboards/Dashboard.json
